# CPTox21: Conformal prediction and exchangeability in in vitro toxicological datasets

This notebooks demonstrates the main workflow to obtain the results for the manuscript ...

### Import libraries and modules

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.svm import SVC
from nonconformist.nc import NcFactory, MarginErrFunc

In [3]:
from cptox21 import (
    define_path, load_signatures_files, StratifiedRatioSampler,CrossValidationSampler,
    KnownIndicesSampler, InductiveConformalPredictor,
    AggregatedConformalPredictor, CPTox21AggregatedConformalPredictor, 
    CPTox21CrossValidator, CPTox21TrainUpdateCrossValidator
)

### Define paths and parameters

In [4]:
data_signatures_path = "../data/data_signatures/"
# data_models_path = args["data_models_path"]
data_statistics_path = "../data/data_statistics/"

In [5]:
endpoint = "NR_ER"

In [6]:
# CP
n_folds_acp = 2

#### Build ICP classifier

In [7]:
clf = SVC(kernel='rbf', C=50, gamma=0.002, probability=True)
error_function = MarginErrFunc()
normaliser_model = None
nc = NcFactory.create_nc(
    clf, err_func=error_function
)
icp = InductiveConformalPredictor(
        nc_function=nc, condition=(lambda instance: instance[1])
    )  # Mondrian as (default) condition)

#### Build ACP for main framework and for train_update

In [8]:
acp = CPTox21AggregatedConformalPredictor(
        predictor=icp, sampler=StratifiedRatioSampler(n_folds=n_folds_acp),
        aggregation_func=np.median
    )

#### Load data

In [9]:
datasets = ["train", "test", "score"]
train_path = define_path(endpoint=endpoint, data=datasets[0], signatures_path=data_signatures_path)
test_path = define_path(endpoint=endpoint, data=datasets[1], signatures_path=data_signatures_path)
score_path = define_path(endpoint=endpoint, data=datasets[2], signatures_path=data_signatures_path)

X_train, y_train, X_test, y_test, X_score, y_score = load_signatures_files(train_path, test_path, score_path)
# X_train = X_train[:500]
# y_train = y_train[:500]

#### Define crossvalidator, which does all acp experiments except for train_update

In [10]:
cross_validator = CPTox21CrossValidator(
            acp, cv_splitter=CrossValidationSampler(),
            score_splitter=StratifiedRatioSampler(test_ratio=0.5)
        )

#### Crossvalidate

In [ ]:
cross_validator.cross_validate(
            steps=10,
            endpoint=endpoint,
            X_train=X_train,
            y_train=y_train,
            X_update=X_test,
            y_update=y_test,
            X_score=X_score,
            y_score=y_score,
        )

len score 245 245


<__array_function__ internals>:5: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.


[[0.54732972 0.23387861]
 [0.93837149 0.03139152]
 [0.53043337 0.2401428 ]
 ...
 [0.7435561  0.13300185]
 [0.90327285 0.05879658]
 [0.76718295 0.12389004]] <class 'numpy.ndarray'>
(1439, 3)
(1439, 3)
[[2.34582202e-01 4.00530071e-01]
 [5.19391394e-01 2.35822968e-01]
 [5.58745363e-02 5.70369173e-01]
 [7.25308282e-01 1.39740297e-01]
 [7.82417536e-01 1.34975341e-01]
 [3.47826715e-02 6.28640605e-01]
 [1.20760737e-01 4.82577420e-01]
 [4.62950050e-01 2.67130264e-01]
 [1.43229770e-01 4.82448354e-01]
 [5.54521310e-01 2.38094706e-01]
 [9.98261127e-02 5.11105367e-01]
 [5.59303499e-01 2.14888459e-01]
 [2.84391974e-01 3.89500817e-01]
 [8.50922454e-01 8.48766586e-02]
 [7.25570779e-02 5.47717218e-01]
 [1.24809846e-02 7.50865524e-01]
 [7.50099115e-01 1.29127178e-01]
 [3.65202782e-01 3.45745059e-01]
 [3.06069411e-01 3.57675409e-01]
 [4.22938982e-01 2.88612096e-01]
 [7.52280364e-01 1.20835158e-01]
 [5.22601624e-01 2.57798505e-01]
 [6.31919226e-01 1.90754839e-01]
 [7.45742926e-01 1.29163389e-01]
 [7.1179

[[0.36394539 0.42375499]
 [0.57564988 0.28976608]
 [0.11797538 0.69696361]
 [0.78762512 0.1814846 ]
 [0.82470862 0.11577767]
 [0.08269045 0.75512377]
 [0.20624003 0.54965469]
 [0.55704688 0.34726824]
 [0.25207528 0.58466001]
 [0.61543223 0.23379543]
 [0.17304263 0.61538425]
 [0.61892223 0.25216353]
 [0.35332486 0.49482374]
 [0.87264813 0.08867031]
 [0.15351413 0.68160439]
 [0.01580332 0.93917462]
 [0.80602361 0.15703331]
 [0.4472427  0.29141656]
 [0.40973344 0.39224846]
 [0.51097591 0.37498225]
 [0.77469493 0.14864013]
 [0.60491346 0.2184822 ]
 [0.67841195 0.19558978]
 [0.78467415 0.18056383]
 [0.76531192 0.15657476]
 [0.77637063 0.17513023]
 [0.45608166 0.2880087 ]
 [0.69203178 0.21160032]
 [0.5006137  0.34988221]
 [0.70754492 0.19886233]
 [0.59834265 0.2408467 ]
 [0.96704334 0.02571093]
 [0.50513684 0.37496378]
 [0.61555769 0.2799584 ]
 [0.32939801 0.43714086]
 [0.29325272 0.49049929]
 [0.43060846 0.34909059]
 [0.8261465  0.13680684]
 [0.92457747 0.09236083]
 [0.19505558 0.63239264]


len score 245 245


<__array_function__ internals>:5: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.


[[0.21175811 0.37258773]
 [0.57226867 0.16166117]
 [0.30681993 0.30340976]
 ...
 [0.1053067  0.48546154]
 [0.36830491 0.25314076]
 [0.27966317 0.32913618]] <class 'numpy.ndarray'>
(1438, 3)
(1438, 3)
[[4.51855390e-01 2.75156092e-01]
 [1.94178690e-01 3.90863435e-01]
 [5.20400333e-02 5.46259230e-01]
 [6.57199289e-01 1.16190944e-01]
 [6.54605686e-01 1.30074312e-01]
 [3.15770600e-02 5.96185154e-01]
 [1.91567464e-01 3.79138522e-01]
 [7.14742310e-01 1.06642350e-01]
 [4.27920716e-01 2.35197579e-01]
 [5.42685451e-01 1.59886589e-01]
 [9.49838266e-02 4.70653702e-01]
 [7.35498576e-01 9.71296372e-02]
 [9.67936795e-02 4.63837121e-01]
 [3.06614537e-02 6.02734152e-01]
 [2.85057326e-01 3.24909810e-01]
 [1.87274620e-02 6.63491707e-01]
 [8.97288879e-01 5.33643142e-02]
 [2.38683887e-01 3.49726220e-01]
 [2.97442243e-01 3.09589291e-01]
 [1.17405843e-01 4.37212531e-01]
 [8.61865528e-01 5.62139484e-02]
 [6.90519887e-01 1.12286084e-01]
 [6.69726088e-01 1.17622190e-01]
 [6.45103626e-01 1.22391654e-01]
 [5.7849

[[0.48114215 0.31562312]
 [0.33009157 0.37163752]
 [0.07143127 0.76363695]
 [0.70153843 0.20364315]
 [0.69887494 0.18898139]
 [0.04169638 0.84599844]
 [0.33985262 0.41278243]
 [0.73694936 0.2029067 ]
 [0.52670703 0.32709186]
 [0.61494558 0.22304285]
 [0.18871649 0.58217114]
 [0.74321504 0.14229202]
 [0.1905575  0.55812366]
 [0.03932406 0.83255122]
 [0.36763613 0.39080502]
 [0.01427502 0.89212917]
 [0.89292663 0.10307292]
 [0.39355088 0.34762119]
 [0.42430578 0.33304454]
 [0.22506478 0.45135267]
 [0.85314007 0.10180313]
 [0.72169029 0.19251601]
 [0.70314309 0.19330413]
 [0.68421962 0.17083689]
 [0.64202277 0.22182002]
 [0.84204025 0.10146843]
 [0.74981369 0.14138457]
 [0.71202956 0.19292044]
 [0.66587599 0.20028473]
 [0.74296999 0.12831661]
 [0.90064092 0.11000281]
 [0.98872459 0.01650562]
 [0.60035939 0.22168081]
 [0.58751871 0.23924399]
 [0.80166828 0.12283366]
 [0.09937793 0.69731627]
 [0.55936463 0.28310017]
 [0.78199773 0.13117417]
 [0.91773708 0.10705354]
 [0.10154985 0.67216467]


len score 245 245


<__array_function__ internals>:5: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.


[[0.84299578 0.06495376]
 [0.93670775 0.03721255]
 [0.95822151 0.03149861]
 ...
 [0.66781203 0.16432757]
 [0.70560694 0.12173623]
 [0.31170741 0.32564837]] <class 'numpy.ndarray'>
(1438, 3)
(1438, 3)
[[4.57017479e-01 2.39086147e-01]
 [3.17171309e-01 3.29851816e-01]
 [5.60130847e-02 5.67384250e-01]
 [1.69476026e-01 4.21781259e-01]
 [5.01923981e-01 2.32837266e-01]
 [3.57302033e-02 6.33459543e-01]
 [3.24968199e-01 3.41350490e-01]
 [2.16841434e-01 3.75937602e-01]
 [2.00714409e-01 4.29377818e-01]
 [6.43607541e-01 1.50974009e-01]
 [5.91177575e-01 1.76917676e-01]
 [8.63530510e-01 6.19214423e-02]
 [3.36914601e-01 3.12271453e-01]
 [3.98198204e-02 6.25301359e-01]
 [3.01538620e-01 3.64058047e-01]
 [1.95150080e-02 6.79613115e-01]
 [8.91461102e-01 5.16311673e-02]
 [4.80711905e-01 2.40814044e-01]
 [4.95159125e-01 2.31189424e-01]
 [5.78423049e-01 1.86846746e-01]
 [8.80869936e-01 5.27209278e-02]
 [7.14865412e-01 1.28898225e-01]
 [5.26263855e-01 2.25491255e-01]
 [5.93931393e-01 1.75447459e-01]
 [7.2361

[[3.96866373e-01 2.90255526e-01]
 [2.70187565e-02 6.56846138e-01]
 [4.23863681e-01 2.88013967e-01]
 [5.55929662e-01 2.04200051e-01]
 [5.44843033e-01 2.09935562e-01]
 [9.43158453e-02 5.14690187e-01]
 [5.15398287e-01 2.03740477e-01]
 [8.97716320e-01 5.02568067e-02]
 [7.54792675e-01 9.74013948e-02]
 [4.64375100e-01 2.46373191e-01]
 [5.59047645e-01 1.97347751e-01]
 [2.88608429e-01 4.49348555e-01]
 [1.53192851e-01 4.46109141e-01]
 [7.47859231e-02 5.40900911e-01]
 [3.65601718e-02 6.29009607e-01]
 [3.35165035e-01 3.16823423e-01]
 [9.32743375e-01 4.01207800e-02]
 [8.02709996e-01 7.90138049e-02]
 [5.36037173e-01 1.99755373e-01]
 [1.86647789e-01 4.39974048e-01]
 [1.18900976e-01 4.97360149e-01]
 [1.71490622e-02 7.05056830e-01]
 [6.67564183e-01 1.50186058e-01]
 [3.41554883e-01 3.01662996e-01]
 [1.39158396e-01 5.66322853e-01]
 [1.46613743e-01 4.56434008e-01]
 [8.59623596e-01 5.05927208e-02]
 [6.79762756e-01 1.28672368e-01]
 [2.91662198e-01 3.66899847e-01]
 [4.86697134e-01 2.17561748e-01]
 [4.702737

[[0.29677547 0.32808519]
 [0.15686613 0.44896851]
 [0.37930649 0.31473969]
 [0.00190082 0.98463402]
 [0.44404545 0.26346746]
 [0.47602936 0.26498762]
 [0.25670114 0.36753479]
 [0.79279828 0.09410153]
 [0.35635301 0.34575129]
 [0.33810389 0.32230904]
 [0.16349949 0.40780628]
 [0.17185001 0.41437448]
 [0.1048239  0.56591004]
 [0.44566236 0.25712453]
 [0.06537802 0.64059474]
 [0.58226921 0.20312179]
 [0.27121075 0.34256502]
 [0.04254787 0.73304289]
 [0.55058514 0.24950579]
 [0.08345638 0.64029489]
 [0.28938965 0.39346888]
 [0.38521708 0.40806972]
 [0.42394234 0.30954947]
 [0.11912091 0.55562626]
 [0.45495007 0.24825108]
 [0.42407979 0.27322197]
 [0.1083319  0.57301914]
 [0.56240467 0.23727356]
 [0.83882725 0.09784689]
 [0.47174407 0.25493345]
 [0.87009272 0.08616586]
 [0.16971389 0.43470172]
 [0.52675362 0.2231066 ]
 [0.67473195 0.14591636]
 [0.55812804 0.18517398]
 [0.53653874 0.2426956 ]
 [0.24005996 0.36613885]
 [0.76338905 0.09375022]
 [0.12841435 0.51329831]
 [0.09097994 0.58888141]


<__array_function__ internals>:5: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.


[[0.36180674 0.31229809]
 [0.41953649 0.37605319]
 [0.34561257 0.31756392]
 ...
 [0.50040255 0.22424158]
 [0.11747369 0.46433835]
 [0.68357997 0.15308182]] <class 'numpy.ndarray'>
(1438, 3)
(1438, 3)
[[1.74524276e-01 4.15367171e-01]
 [5.59423003e-01 2.06594913e-01]
 [3.13575850e-01 3.37808141e-01]
 [2.70935028e-01 3.97125033e-01]
 [7.18677389e-01 1.38899061e-01]
 [4.02343963e-02 5.84805950e-01]
 [2.07298935e-01 3.95264181e-01]
 [6.21194562e-01 1.88891288e-01]
 [5.46851107e-01 2.12690687e-01]
 [6.23560025e-01 1.87465799e-01]
 [1.21069468e-01 4.50366403e-01]
 [5.82498443e-01 1.94109757e-01]
 [1.25008424e-01 4.56716787e-01]
 [4.35894674e-02 5.74144325e-01]
 [9.75273847e-02 5.11548458e-01]
 [2.39281914e-02 6.56595611e-01]
 [9.06698032e-01 4.83655396e-02]
 [4.69520295e-01 2.43513093e-01]
 [1.84852658e-01 4.10774032e-01]
 [5.83970334e-01 2.05135204e-01]
 [7.96347886e-01 1.13296505e-01]
 [4.21999850e-01 2.94254341e-01]
 [3.13899822e-01 3.34031841e-01]
 [2.16170314e-01 3.97479686e-01]
 [7.1324

[[3.32402396e-01 4.52962680e-01]
 [6.15182353e-01 2.35565467e-01]
 [4.41850126e-01 3.83284742e-01]
 [3.26690779e-01 5.14858604e-01]
 [7.63867476e-01 1.48688724e-01]
 [7.25782269e-02 7.74647175e-01]
 [3.69811957e-01 4.71464078e-01]
 [6.81740379e-01 2.02340893e-01]
 [6.19196096e-01 2.82949324e-01]
 [7.08994016e-01 1.77713903e-01]
 [2.51298416e-01 5.13483678e-01]
 [6.34603520e-01 2.46434571e-01]
 [2.63083971e-01 5.00793595e-01]
 [8.55324676e-02 7.57064672e-01]
 [1.98274343e-01 6.44022589e-01]
 [2.89589427e-02 9.18047836e-01]
 [9.34155706e-01 1.99195789e-02]
 [5.57498339e-01 2.97161545e-01]
 [3.47831898e-01 4.74297308e-01]
 [6.48477638e-01 2.36152360e-01]
 [8.43628048e-01 1.00135025e-01]
 [5.44086814e-01 3.54315008e-01]
 [4.36683430e-01 3.79769959e-01]
 [3.76875646e-01 3.87174543e-01]
 [7.58354008e-01 1.63548134e-01]
 [8.19756593e-01 1.06913876e-01]
 [6.68966926e-01 2.18994366e-01]
 [6.69775398e-01 2.10094001e-01]
 [6.42065544e-01 2.42700764e-01]
 [7.22776826e-01 1.77465133e-01]
 [6.842575

len score 245 245


<__array_function__ internals>:5: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.


#### Get splits from crossvalidator, so that exactly the same splits can be used for train_update

In [ ]:
train_index, test_index = cross_validator.train_indices, cross_validator.test_indices

known_indices_sampler = KnownIndicesSampler(known_train=train_index, known_test=test_index)



#### Define ACP for train_update

In [ ]:
train_update_acp = AggregatedConformalPredictor(
        predictor=icp, sampler=StratifiedRatioSampler(n_folds=n_folds_acp),
        aggregation_func=np.median
    )

#### Define train_update crossvalidator using same splits as before and crossvalidate

In [ ]:
train_update_cross_validator = CPTox21TrainUpdateCrossValidator(train_update_acp, cv_splitter=known_indices_sampler)

train_update_cross_validator.cross_validate(steps=10,
                                           endpoint=endpoint,
                                           X_train=X_train,
                                           y_train=y_train,
                                           X_update=X_test,
                                           y_update=y_test,
                                           X_score=X_score,
                                           y_score=y_score,
                                           class_wise_evaluation=False)

### Plots

In [ ]:
plots = {}

In [ ]:
plots["cv"] = cross_validator.calibration_plot( averaged_evaluation_df=cross_validator.averaged_evaluation_df_cv,
            endpoint=endpoint,
        )
plots["pred_score"] = cross_validator.calibration_plot(
            averaged_evaluation_df=cross_validator.averaged_evaluation_df_pred_score,
            endpoint=endpoint,
        )
plots["pred_test"] = cross_validator.calibration_plot(
            averaged_evaluation_df=cross_validator.averaged_evaluation_df_pred_test,
            endpoint=endpoint,
        )
plots["cal_update"] = cross_validator.calibration_plot(
            averaged_evaluation_df=cross_validator.averaged_evaluation_df_pred_cal_update,
            endpoint=endpoint,
        )
plots["cal_update2"] = cross_validator.calibration_plot(
            averaged_evaluation_df=cross_validator.averaged_evaluation_df_pred_cal_update2,
            endpoint=endpoint,
        )
plots["train_update_cv"] = train_update_crossvalidator.calibration_plot(
            averaged_evaluation_df=train_update_crossvalidator.averaged_evaluation_df_cv,
            endpoint=endpoint,
        )
plots["train_update_pred_score"] = train_update_crossvalidator.calibration_plot(
            averaged_evaluation_df=train_update_crossvalidator.averaged_evaluation_df_pred_score,
            endpoint=endpoint,
        )